### ISSUE TITLE
Automatic Dependency Injection for flamework classes runs multiple times

### ISSUE THREAD

**Issue by murmanox** [rbxts-flamework/vscode#2]
When injecting a dependency for a class that has no constructor, multiple constructors will sometimes be created. When adding a dependency to an existing constructor, it will be added multiple times.

**Comment by Fireboltofdeath** [comment]
Unfortunately, I believe this is a vscode/TS bug. The language extensions get activated multiple times by TypeScript.

I can look into workarounds but it's a bit trickier given how language service plugins work.

**Comment by Fireboltofdeath** [comment]
https://github.com/rbxts-flamework/lsp/commit/88c0650d7a431bc4824f3186ea9f49712ac56a3d
