### ISSUE TITLE
It breaks the intellisense

### ISSUE THREAD

**Issue by howmanysmall** [rbxts-flamework/vscode#4]
Type: <b>Bug</b>

To reproduce it, you simply just need to type out the following:

```ts
@Service({})
class Test {
	public guh(tryToTypeNumberAsTheType) {}
}
```

It doesn't show the autocomplete for number at all.

Extension version: 0.1.2
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'wsl+ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (6.77GB free)|
|Process Argv|--crash-reporter-id bb38f29f-502a-46f7-9851-648d8742f996|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+ubuntu' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
8082a590:30971561
edj9j583:30969295
fegfb526:30973843
ccp2r6:30958158
dsvsc020:30973508

```

</details>

**Comment by Fireboltofdeath** [comment]
This is a feature in Flamework called `Smarter Intellisense` where it'll try to hide intellisense items when they don't make sense, e.g by only including other singletons in the constructor of singletons.

You can disable this in the settings, or use `@metadata injectable` on one of your own types to include it in the smarter intellisense.
